version: '3'
services:
  api:
    build:
     context: .
     dockerfile: api/Dockerfile
    expose:
     - '5000'
    ports:
      - "5000:5000"
    container_name: api
    command: npm run dev
    env_file:
       - api/.env  
  web:
    # build: web
    build:
      context: ./
      dockerfile: web/Dockerfile
    ports:
      - "8080:8080"
    # links:
    #   - api
    container_name: web
    # env_file:
    #   - .env