version: '3'
services:
  api:
    build:
      context: ./
      dockerfile: api/Dockerfile
    ports:
      - "5000:5000"
    container_name: api
  web:
    build:
      context: ./
      dockerfile: web/Dockerfile
    ports:
      - "8080:8080"
    container_name: web
    env_file:
      - web/.env