version: '3'
services:
  api:
    build:
      context: ./
      dockerfile: api/Dockerfile
    ports:
      - "5000:5000"
    container_name: api
    # env_file:
    #   - .env
  web:
    build:
      context: ./
      dockerfile: web/Dockerfile
    ports:
      - "8080:8080"
    # links:
    #   - api
    container_name: web
    # env_file:
    #   - .env