name: API CI


on:
  pull_request:
    branches:
      - main
      - dev
    paths:
      - "api/**"
      - ".github/workflows/api-ci.yaml"

defaults:
  run:
    shell: bash

jobs:
  docker-build-check:
    runs-on: ubuntu-20.04
    name: Build dockerfile to ensure it works

    steps:
      - uses: actions/checkout@v2
      - name: docker build to check strictness
        id: docker-build
        run: |
          docker build -t cc-api . -f api/Dockerfile 

  node-run-tests:
    runs-on: ubuntu-latest
    name: Build api natively and run unit tests

    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: npm install
        working-directory: api/
      - name: Run tests
        run: npm run test
        working-directory: api/